### ISSUE TITLE
Disable alert about exceeding max upload size

### ISSUE THREAD

**Issue by piotrpog** [sebastian-lenz/craft-chunked-uploads#1]
When i want to upload file using assets browser, alert about exceeding file size limit still appears, even if this plugin should theoretically allow uploading files exceeding this limit.

**Comment by matthewstick** [comment]
this is happening for me too

**Comment by thisisjamessmith** [comment]
Are there any workarounds for this?

**Comment by thisisjamessmith** [comment]
Went through debugging this, and it looks like it's caused by the fact that the string "admin/" is hardcoded here: https://github.com/sebastian-lenz/craft-chunked-uploads/blob/master/src/assets/resources/fileupload.patch.js#L4-L5
-- but if you've renamed your Craft CP trigger to something else, that's going to break. Changing those to match your `cpTrigger` fixes it. Or perhaps the correct fix seems to be using `Craft.cpTrigger`:

```js
    Craft.cpTrigger + '/actions/assets/save-asset',
    Craft.cpTrigger + '/actions/assets/upload',
```
